# Base configuration for a 10M parameter model training run
output_dir: "models/25M"
train_dataset_path: "data/tokenized/25M/train"

# --- Model ---
tokenizer_path: "tokenizer/25M"
model_arch_type: "gpt2"
train_from_scratch: true
model_size_tag: "gpt2-100m"

# --- Training Hyperparameters ---
num_train_epochs: 1
per_device_train_batch_size: 8
gradient_accumulation_steps: 16
learning_rate: 5e-4
weight_decay: 0.01
max_grad_norm: 1.0
lr_scheduler_type: "cosine"
num_warmup_steps: 100

# --- Logging & Saving ---
logging_steps: 5
save_steps: 3

# --- Hardware & Seed ---
use_amp: true
num_workers: 4
seed: 42

checkpoint_schedule:
- 1
- 2
- 4
- 8
- 16
- 32
- 64
- 128
- 192
- 256
- 384
- 512
- 598
- 683
- 853
- 1024
- 1126
- 1229
- 1332
- 1434
- 1536
- 1638
- 1740
- 1843
- 1946
- 2048
- 2156
- 2263
- 2370
- 2477
- 2584
- 2692
- 2799
- 2906
- 3014
- 3121
- 3380
- 3639
- 3898
- 4157
- 4416
- 4675
- 4934
- 5193
- 5452
- 5711
- 5970
- 6229
- 6488
- 6747